---
knit: "bookdown::render_book"
---

<!-- *************************************************** -->
<!-- PRELIMINARY PAGES -->
<!-- *************************************************** -->
<!-- The instructions contained within this part of the thesis template need to be suppressed from the final thesis. There are instructions on how to do this in the Mainthesis.tex file. -->

<!-- To ensure your work is not suppressed with the instructions please add your text only where instructed. -->

<!-- We use the Latex \section*{} here rather than R Markdown ## to ensure that each heading doesn't appear in the Table of Contents -->

<!-- *** Publications included in this thesis *** -->
\section*{Publications included in this thesis}

 <!-- *************************************************** -->
 <!-- PRELIMINARY PAGES -->
 <!-- *************************************************** -->
 <!-- The instructions contained within this part of the thesis template need to be suppressed from the final thesis. There are instructions on how to do this in the Mainthesis.tex file. -->

 <!-- To ensure your work is not suppressed with the instructions please add your text only where instructed. -->
```{block prelim-publications, include = params$instructions}

Start this section on a new page [this template will automatically handle this]. \newline
	
\noindent
If you choose to include publications as part of your thesis as described in UQ policy (\href{http://ppl.app.uq.edu.au/content/4.60.07-alternate-thesis-format-options}{\color{blue}{PPL 4.60.07 Alternative Thesis Format Options}}) use this section to detail accepted or in press publication/s using the standard citation format for your discipline. \newline
    
\noindent
Papers submitted for publication and awaiting review should appear in the next section, \textbf{Submitted manuscripts included in this thesis}. \newline
    
\noindent
On the page immediately preceding the chapter that includes your publication, in no more than one (1) page, describe your contribution to the authorship if you are not a sole author. In describing your contribution, you must satisfy the University's authorship policy (\href{http://ppl.app.uq.edu.au/content/4.20.04-authorship}{\color{blue}{PPL 4.20.04 Authorship}}). Authorship is based on having made a substantive contribution to at least one, and usually more than one, of the following activities:

\begin{enumerate}
	\item	conception and design of the project;
	\item	analysis and interpretation of the research data on which the publication is based;
	\item	drafting significant parts of the publication or critically reviewing it so as to contribute to the interpretation.
\end{enumerate}
	
\noindent
As an author, you must have participated sufficiently in the publication to take public responsibility for at least that part of the work that you contributed. \newline
    
\noindent
It may be useful to refer to specific parts of the methods, analyses, results, or discussion to illustrate your contribution to the paper. \newline
    
\noindent
If you have not included any of your publications in the thesis then state ``No publications included''. \newline
	
\textbf{Example:}
\begin{enumerate}

  \item \cite{DumyCitationKey} \textbf{Your Name}, Co-author 1, and Final Author, \href{linktoyourpaper}{Title of your paper}, \textit{Journal}, Issue, Number, Year

  \item \cite{DumyCitationKey} \textbf{Your Name}, Co-author 1, and Final Author, \href{linktoyourpaper}{Title of your paper}, \textit{Journal}, Issue, Number, Year

\end{enumerate}
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Submitted manuscripts included in this thesis *** -->
\section*{Submitted manuscripts included in this thesis}

```{block prelim-manuscripts, include = params$instructions}

List manuscript/s submitted for publication here. As described above for \textbf{Publications included in the thesis}, on the page immediately preceding the chapter that includes the submitted manuscript, in no more than one (1) page, detail your contribution to the authorship if you are not the sole author. \newline
    
\noindent
If you have no submitted manuscripts from your candidature then state ``No manuscripts submitted for publication''. \newline
    
\textbf{Example:}
\begin{enumerate}
  
\item \cite{DumyCitationKey} \textbf{Your Name}, Co-author 1, and Final Author, Title of your paper, submitted to \textit{Journal} on 4th June2018.
  
\end{enumerate}
```
<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Other publications during candidature *** -->
\section*{Other publications during candidature}

```{block prelim-otherpubs, include = params$instructions}

List other publications arising during your candidature using the standard citation format for your discipline. Divide your publications into sub-sections as appropriate in your discipline \eg{} peer-reviewed papers, book chapters, conference abstracts. Papers submitted for publication and awaiting review are not considered publications and cannot be included in this section.\newline
    
\noindent
If you have no publications from your candidature then state ``No other publications''.\newline
    
\textbf{Example:}
\subsection*{Conference abstracts}

\begin{enumerate}

  \item \cite{DumyCitationKey} \textbf{Your Name}, Co-author 1, and Final Author, Title of your conference paper, \textit{Proceedings of Conference}, other details.

\end{enumerate}

\subsection*{Book chapters}

\begin{enumerate}

  \item \cite{DumyCitationKey} \textbf{Your Name}, Co-author 1, and Final Author, Title of your chapter, Book, editor, \etc{}.

\end{enumerate}
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Contributions by others to the thesis *** -->
\section*{Contributions by others to the thesis}

```{block prelim-othercontrib, include = params$instructions}

List the significant and substantial inputs made by others to the research, work and writing represented and/or reported in the thesis. These could include significant contributions to: the conception and design of the project; non-routine technical work; analysis and interpretation of research data; drafting significant parts of the work or critically revising it so as to contribute to the interpretation. \newline
    
\noindent
If no one contributed significantly then state ``No contributions by others''.
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Statement of parts of the thesis submitted to qualify for the award of another degree *** -->
\section*{Statement of parts of the thesis submitted to qualify for the award of another degree}

```{block prelim-otheraward, include = params$instructions}

The thesis must be comprised only of research undertaken while enrolled in the HDR program unless otherwise approved by the Dean, Graduate School in advance of submission.\newline
    
\noindent
If you have been given permission to include your previous work that has been used towards another degree, you must list the relevant parts of the thesis that incorporates this work including, the degree name, year and institution, and the outcome of the submission of material. \newline
    
\noindent
If no parts of the thesis have been submitted in this way then state ``No works submitted towards another degree have been included in this thesis''.
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Research involving human or animal subjects *** -->
\section*{Research involving human or animal subjects}

```{block prelim-humananimals, include = params$instructions}

All research involving human or animal subjects requires prior ethical review and approval by an independent review committee. At UQ, the relevant committee for research involving human subjects is the \href{http://www.uq.edu.au/research/integrity-compliance/human-ethics}{\color{blue}{Human Ethics Unit}} and the relevant committee for research involving animal subjects is the relevant \href{http://www.uq.edu.au/research/integrity-compliance/animal-welfare}{\color{blue}{Animal Ethics Committee}}.  Please provide details of any ethics approvals obtained including the ethics approval number and name of approving committees.  A copy of the ethics approval letter must be included in the thesis appendix.\newline
    
\noindent
If no human or animal subjects were involved in this research please state: ``No animal or human subjects were involved in this research''.
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

\clearpage

<!-- *** Acknowledgements *** -->
\section*{Acknowledgements}

```{block prelim-acknowledgements, include = params$instructions}

Start this section on a new page [the template will handle this for you].\newline
    
\noindent
Acknowledgements recognise those who have been instrumental in the completion of the project.  Acknowledgements should include any professional editorial advice received including the name of the editor and a brief description of the service rendered.
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

\clearpage

<!-- *** Financial Support *** -->
\section*{Financial Support}

```{block prelim-financial, include = params$instructions}
Start this section on a new page [the template will handle this for you].\newline
    
\noindent
If you are the recipient of an Australian Government Research Training Program (RTP) scholarship, you are required to acknowledge thicontribution.  Please include the text below:\newline

\noindent
``This research was supported by an Australian Government Research Training Program Scholarship''\newline

\noindent
If you received any other financial support for your project, you are also required to acknowledge the funding body/bodies in thisection.\newline

\noindent
If no financial provided then state ``No financial support was provided to fund this research''.
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->


<!-- *** Keywords *** -->
\section*{Keywords}

```{block prelim-keywords, include = params$instructions}

	Maximum 10 words; use lower case throughout, separating words/phrases with commas. For example: word, word word, word, word, word word
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Australian and New Zealand Standard Research Classifications (ANZSRC) *** -->
\section*{Australian and New Zealand Standard Research Classifications (ANZSRC)}

```{block prelim-ANZSRC, include = params$instructions}

Provide data that links your thesis to the disciplines and discipline clusters in the Federal Government’s Excellence in Research for Australia (ERA) initiative.\newline
    
\noindent
Please allocate the thesis a \textbf{maximum of 3} \href{http://www.abs.gov.au/Ausstats/abs@.nsf/Latestproducts/6BB427AB9696C225CA2574180004463E?opendocument}{\color{blue}{Australian and New Zealand Standard Research Classifications (ANZSRC) codes}} at the \textbf{6 digit level} and include the descriptor and a percent weighting for each code. Total percent must add to 100.\newline


\textbf{Example:}\newline


ANZSRC code: 060101, Analytical Biochemistry, 60\% \newline
\indent ANZSRC code: 060104, Cell Metabolism, 20\% \newline
\indent ANZSRC code: 060199, Biochemistry and Cell Biology not elsewhere classified, 20\%
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Fields of Research (FoR) Classification *** -->
\section*{Fields of Research (FoR) Classification}

```{block prelim-FoR, include = params$instructions}

Allows for categorisation of the thesis according to the field of research. \newline

\noindent
Please allocate the thesis a \textbf{maximum of 3\href{http://www.abs.gov.au/Ausstats/abs@.nsf/Latestproducts/6BB427AB9696C225CA2574180004463E?opendocument}{\color{blue}{Fields of Researc(FoR) Codes}} at the \textbf{4 digit level} and include the descriptor and a percent weighting for each code. Total percent must add to 100\newline

\textbf{Example:}\newline

FoR code: 0601, Biochemistry and Cell Biology, 80\% \newline
\indent FoR code: 0699, Other Biological Sciences, 20\%
```

<!-- ********* Enter your text below this line: ******** -->



<!-- *************************************************** -->

<!-- *** Order of remaining thesis content *** -->
```{block prelim-orderremain, include = params$instructions}

\section*{Order for the Remainder of the Thesis}
\noindent
Remainder of the thesis should be in the following order

\begin{itemize}
  \item Dedications (if applicable)
  \item Table of Contents
  \item List of Figures and Tables
  \item List of Abbreviations used in the thesis
  \item Main text of the thesis
  \item Bibliography or List of References
  \item Appendices
\end{itemize}

\noindent
\textbf{Date of thesis template release:} 22 March 2019
```

\clearpage

<!-- *** Dedication *** -->
<!-- If you wish to add a dedication (if appropriate), do so here. -->
<!-- If not, comment out from here... -->
\rmfamily
\normalfont

\begin{vplace}[1]
	\begin{center}
		This template is dedicated to nerds everywhere.
	\end{center}
\end{vplace}
<!-- ... to here. -->

\clearpage
\pagestyle{headings}

<!-- *** Table of Contents *** -->
<!-- These generate the table of contents, list of figures, and list of tables from items tagged with a \label{} command. -->
\tableofcontents
	\clearpage
\listoffigures
	\clearpage
\listoftables

<!-- List of symbols. Included if params: symbols is set to TRUE in Index.RMD -->
``` {r, abbreviations-symbols, child = if (params$symbols) "00-symbols.Rmd"}
```

<!-- ***End of front matter *** -->

<!-- The following line is required to re-set page numbering after preliminary material. Do not remove-->
\clearpage\pagenumbering{arabic}\setcounter{page}{0}

\mainmatter
